---
platform: linux
image: docker:///boshcpi/aws-cpi-release
inputs:
- name: stemcell
- name: bosh-cpi-src
- name: bats
- name: deployment
run:
  path: bosh-cpi-src/ci/tasks/run-bats.sh
params:
  base_os:                      replace-me
  aws_access_key_id:            replace-me
  aws_secret_access_key:        replace-me
  region_name:                  replace-me
  stack_name:                   replace-me
  BAT_VCAP_PASSWORD:            replace-me
  BAT_STEMCELL_NAME:            replace-me
  public_key_name:              replace-me
